### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by somebodyus** [qubvel/segmentation_models.pytorch#287]
`RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

I have tried many pytorch versions. The error is still there. Could anyone help me?

**Comment by jutu1398** [comment]
@somebodyus 

I'm having the same issue, also using PyTorch. Seems to be an issue because I am using an RTX 3080? Currently debugging, and I'll let you know if I find anything.

**Comment by somebodyus** [comment]
> @somebodyus
> 
> I'm having the same issue, also using PyTorch. Seems to be an issue because I am using an RTX 3080? Currently debugging, and I'll let you know if I find anything.

I just solved this issue by downgrading pytorch to 1.5. Hope it could help others.
